# Generated by Django 4.1.4 on 2022-12-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_fanlar_kategoriya'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('text', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.kategoriya')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.fanlar')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': '4. Barcha fayllar',
            },
        ),
    ]
