# Generated by Django 4.1.4 on 2022-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
